<?php


use Phinx\Seed\AbstractSeed;

class LocalSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $this->seedUsers();
        $this->seedBikes();
        $this->seedReservations();
    }

    private function seedUsers()
    {
        $data = [
            [
                'id' => 1,
                'email' => 'cinda.erbe@yahoo.com',
                'password' => '$2y$10$zcRIq4Pe8MMmnlBE.lqFPOwYJHy8DokdjE/gDTVIIVSlJjezMcHGm',
                'first_name' =>'Cinda',
                'last_name' => 'Erbe',
                'birthday' => '1970-01-05',
                'rides' => 14,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 2,
                'email' => 'hal.martello@outlook.com',
                'password' => '$2y$10$U99C4yROVf9a16TQyDDx9eMciswcOTTWGyR5At2jnsMuPoZ63M67S',
                'first_name' =>'Hal',
                'last_name' => 'Martello',
                'birthday' => '1970-06-29',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 3,
                'email' => 'myong.nalls@outlook.com',
                'password' => '$2y$10$fZrDkoFa3H7.K8BO9HvF4uX.Rsaw0GqhDPtJx9hyrcP3y8TCWxOrq',
                'first_name' =>'Myong',
                'last_name' => 'Nalls',
                'birthday' => '1971-08-22',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 4,
                'email' => 'laurice.simonton@hotmail.com',
                'password' => '$2y$10$XgRzRMDSMgHV5x.oaUfomeajRnSpt2UCtWKm2pSsDS93lIiHz2LLK',
                'first_name' =>'Laurice',
                'last_name' => 'Simonton',
                'birthday' => '1971-08-31',
                'rides' => 2,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 5,
                'email' => 'sherrie.goodall@hotmail.com',
                'password' => '$2y$10$uF8ZRFYBVq.u5uoHT8vJte1pLVK7wEI7DsPX5tIYUlgZ.N2idhFc.',
                'first_name' =>'Sherrie',
                'last_name' => 'Goodall',
                'birthday' => '1971-10-20',
                'rides' => 4,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 6,
                'email' => 'clare.linkous@yahoo.com',
                'password' => '$2y$10$QWm3uT2k5/YBnLhY4kG7a.A2pvUHG4B9OrGUnqakYNEkF0.89cnJ6',
                'first_name' =>'Clare',
                'last_name' => 'Linkous',
                'birthday' => '1972-02-13',
                'rides' => 9,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 7,
                'email' => 'lucinda.wasser@hotmail.com',
                'password' => '$2y$10$6al1aA0OoyMGJcDtNJ1qKeSXPR7jG469RPJTZJVIhkBiXJdCDjZ6u',
                'first_name' =>'Lucinda',
                'last_name' => 'Wasser',
                'birthday' => '1973-12-13',
                'rides' => 13,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 8,
                'email' => 'christeen.lepore@outlook.com',
                'password' => '$2y$10$0MGnjBkaX0wO7dykVEq1IeGHnvW9Mnv8RCvH0KFGypZp1yJYfxCnC',
                'first_name' =>'Christeen',
                'last_name' => 'Lepore',
                'birthday' => '1981-12-25',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 9,
                'email' => 'cheryle.clow@outlook.com',
                'password' => '$2y$10$q4GE85.EY6F5MZFHq23LQeyosdOMLGk1V4tuYL.Ajxvb75iKOXX5y',
                'first_name' =>'Cheryle',
                'last_name' => 'Clow',
                'birthday' => '1983-05-02',
                'rides' => 1,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 10,
                'email' => 'minnie.studley@aol.com',
                'password' => '$2y$10$oGe9J5.tAoERHm68uWQVteAClhLIAOtmPSkQp4xgi4MtzEjt56h1u',
                'first_name' =>'Minnie',
                'last_name' => 'Studley',
                'birthday' => '1983-07-02',
                'rides' => 8,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 11,
                'email' => 'marilyn.vanallen@gmail.com',
                'password' => '$2y$10$mI/nqTHQOawnAzQw5uEoxuLmzPY80cdko1PGrG7pWU8TDJBGD7rIe',
                'first_name' =>'Marilyn',
                'last_name' => 'Vanallen',
                'birthday' => '1984-03-10',
                'rides' => 20,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 12,
                'email' => 'stephnie.dimeo@yahoo.com',
                'password' => '$2y$10$JZq165yo0nQomykENbxNH.s5LtiodrzK33Uzgz4TNgcWaDNGL5z42',
                'first_name' =>'Stephnie',
                'last_name' => 'Dimeo',
                'birthday' => '1984-12-07',
                'rides' => 19,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 13,
                'email' => 'freeda.kornegay@yahoo.com',
                'password' => '$2y$10$Nv7FoOJnENVbQqX0QjF4DOKjrXWtWajOsIKTlt0DdFcTFSqvMUAI6',
                'first_name' =>'Freeda',
                'last_name' => 'Kornegay',
                'birthday' => '1985-07-03',
                'rides' => 1,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 14,
                'email' => 'nina.mcgarry@aol.com',
                'password' => '$2y$10$aNYFJgBRZEh4RD/KrfDcGen4rK3fAzOOwTLquVICbbPx2eojsjwE6',
                'first_name' =>'Nina',
                'last_name' => 'Mcgarry',
                'birthday' => '1986-02-19',
                'rides' => 1,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 15,
                'email' => 'harriette.pisani@outlook.com',
                'password' => '$2y$10$ipn2WpEWwv.I0XCGg1ej7OD3mSQc63PCW8WQPfkj02TUBVKcf8bD.',
                'first_name' =>'Harriette',
                'last_name' => 'Pisani',
                'birthday' => '1986-10-29',
                'rides' => 18,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 16,
                'email' => 'long.boden@aol.com',
                'password' => '$2y$10$Km2QDcIMvBvahy6egKC9c.VF9STJHRkFBq7WPonXb7wqIo/1o6ACa',
                'first_name' =>'Long',
                'last_name' => 'Boden',
                'birthday' => '1988-04-27',
                'rides' => 16,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 17,
                'email' => 'candie.nesbit@hotmail.com',
                'password' => '$2y$10$oMfj3nwlJ6WrtM8LgtHBOOtLnqdCYgoTXpMlVOgT9KPWcCmnWfoVW',
                'first_name' =>'Candie',
                'last_name' => 'Nesbit',
                'birthday' => '1989-11-03',
                'rides' => 1,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 18,
                'email' => 'deangelo.perone@hotmail.com',
                'password' => '$2y$10$OPT27HoyW7wIAXfwd0ZjGenKkWWqK3nc.P0lK.mwaM2rQwB3W5vYS',
                'first_name' =>'Deangelo',
                'last_name' => 'Perone',
                'birthday' => '1992-12-30',
                'rides' => 5,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 19,
                'email' => 'jarod.farnsworth@gmail.com',
                'password' => '$2y$10$SNSh62Mt.aqn5O5iQmLc3uGclK81omJY4pCDz/cYoJ0ZBq.uj1dcS',
                'first_name' =>'Jarod',
                'last_name' => 'Farnsworth',
                'birthday' => '1993-01-01',
                'rides' => 10,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 20,
                'email' => 'clarisa.holyfield@outlook.com',
                'password' => '$2y$10$n288pUi3gDN3ytvvjV.xDOP4NBfbIy9NxNaMoNuMCzUk9mf2XHHv6',
                'first_name' =>'Clarisa',
                'last_name' => 'Holyfield',
                'birthday' => '1995-03-10',
                'rides' => 9,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 21,
                'email' => 'darryl.bivens@aol.com',
                'password' => '$2y$10$7Uz6ShAlPp6Y..mKgU3k2.CegvsYSVnDK0GJWcNw3x2WCkSBoVa.u',
                'first_name' =>'Darryl',
                'last_name' => 'Bivens',
                'birthday' => '1997-02-23',
                'rides' => 0,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 22,
                'email' => 'milan.vigue@outlook.com',
                'password' => '$2y$10$OdcS2RB5NsEp5hjGKl2Zeey03mcPNWcSJKqZFKcIFA0W.8Pak9PQq',
                'first_name' =>'Milan',
                'last_name' => 'Vigue',
                'birthday' => '1997-06-10',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 23,
                'email' => 'aurea.falgoust@yahoo.com',
                'password' => '$2y$10$cYXkkmQLRbE6.gKgzgM2J.2sF9lXurkf.41.dCehyGVMTYJc1X6m2',
                'first_name' =>'Aurea',
                'last_name' => 'Falgoust',
                'birthday' => '1997-08-24',
                'rides' => 0,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 24,
                'email' => 'torri.abate@hotmail.com',
                'password' => '$2y$10$vd4McK9ANnReEWqkloXf8eVXJSH3KMw.iDqQpJo6Pcfl.L.Pi9jdK',
                'first_name' =>'Torri',
                'last_name' => 'Abate',
                'birthday' => '1998-12-28',
                'rides' => 3,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 25,
                'email' => 'shaun.pates@outlook.com',
                'password' => '$2y$10$FDxhA/kjQvaMelmf3BGaJeQlAln6loM9U3O3K/Q47b0QTCs72XXwK',
                'first_name' =>'Shaun',
                'last_name' => 'Pates',
                'birthday' => '1999-02-15',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 26,
                'email' => 'kori.hagemeier@outlook.com',
                'password' => '$2y$10$7FFzlBLveHnpSqQrVpumB..YrdYXuP2d.9j0t0oGosirj6sBdo27m',
                'first_name' =>'Kori',
                'last_name' => 'Hagemeier',
                'birthday' => '1973-05-09',
                'rides' => 3,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 27,
                'email' => 'shona.santigo@gmail.com',
                'password' => '$2y$10$6UFe0k2pEp004hWDwWKKv.AqxwJ61t.ewHVXcESwrYLKhd4U0NJ0e',
                'first_name' =>'Shona',
                'last_name' => 'Santigo',
                'birthday' => '1973-08-30',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 28,
                'email' => 'yoshiko.loflin@aol.com',
                'password' => '$2y$10$AM815YWN8evim3F1iFJYourJXFSZOF.wWmXUqUG/tlGdpmgxVfIvm',
                'first_name' =>'Yoshiko',
                'last_name' => 'Loflin',
                'birthday' => '1976-03-18',
                'rides' => 14,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 29,
                'email' => 'carita.montealegre@aol.com',
                'password' => '$2y$10$hpTr0okECKdW.eLX/PqIxO7Sm1fB3sxGR1PrCX1cjZv0bGvwkjZCm',
                'first_name' =>'Carita',
                'last_name' => 'Montealegre',
                'birthday' => '1977-05-23',
                'rides' => 0,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 30,
                'email' => 'francesco.das@outlook.com',
                'password' => '$2y$10$KBPKqFeYc3J6yph40gQE2OO286vPANauJI2iyMLqfX.jpd7p.IztK',
                'first_name' =>'Francesco',
                'last_name' => 'Das',
                'birthday' => '1978-05-20',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 31,
                'email' => 'yee.lasalle@yahoo.com',
                'password' => '$2y$10$xS1d3VbX/M.6vVdUNIFjbe40hBZNF2egdBTVhyOqlmAEjnNZzdraq',
                'first_name' =>'Yee',
                'last_name' => 'Lasalle',
                'birthday' => '1978-06-10',
                'rides' => 8,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 32,
                'email' => 'gavin.harari@outlook.com',
                'password' => '$2y$10$YrubKpmbyTR5BSKKtpKgEuz.c4hktNWH1JO/0NON7/6skq1BeIdsO',
                'first_name' =>'Gavin',
                'last_name' => 'Harari',
                'birthday' => '1978-06-19',
                'rides' => 7,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 33,
                'email' => 'loriann.michaud@yahoo.com',
                'password' => '$2y$10$wjn9rW9wB0V.0K20.9crb.KtA8biAT.nHoCnJ0.VLIzZq3IIzMyhC',
                'first_name' =>'Loriann',
                'last_name' => 'Michaud',
                'birthday' => '1981-11-29',
                'rides' => 9,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 34,
                'email' => 'joycelyn.samples@yahoo.com',
                'password' => '$2y$10$Cb5ipkY534BwfP4IaDVMGeXC/pFlKUPmE8vVsERWDfWCqCXxJZ0JS',
                'first_name' =>'Joycelyn',
                'last_name' => 'Samples',
                'birthday' => '1984-05-13',
                'rides' => 24,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 35,
                'email' => 'maricruz.nickelson@gmail.com',
                'password' => '$2y$10$Tzak8X3lgEoGr4DNf.0FQ.eij16TFlQV4lvtNe3DKMajQ/zPa82.y',
                'first_name' =>'Maricruz',
                'last_name' => 'Nickelson',
                'birthday' => '1985-08-06',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 36,
                'email' => 'yolonda.banfield@gmail.com',
                'password' => '$2y$10$UFY/uAQKvbLra6mMQQj0RuUmnMCjkxJBkA1x4qC91pSNyARIK5CZq',
                'first_name' =>'Yolonda',
                'last_name' => 'Banfield',
                'birthday' => '1987-03-20',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 37,
                'email' => 'carl.foxx@outlook.com',
                'password' => '$2y$10$k30JUQ/tl1dx9KpauXmAqeElHUYW0P4p.9NvhUL3Sr3LVpbnhNZMe',
                'first_name' =>'Carl',
                'last_name' => 'Foxx',
                'birthday' => '1987-11-21',
                'rides' => 16,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 38,
                'email' => 'brendan.lusher@outlook.com',
                'password' => '$2y$10$6Cf4wJ1cQOZ/hLPhDTqMJeRCHOhAQ18BPfbUa4qyLsnlFMcRXvKx6',
                'first_name' =>'Brendan',
                'last_name' => 'Lusher',
                'birthday' => '1989-04-24',
                'rides' => 23,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 39,
                'email' => 'irma.rael@outlook.com',
                'password' => '$2y$10$6PpUHK3jVewkAd0dGHIEKeq/gQrtLta55pj/ZFdbYxv4PkzWdBrMS',
                'first_name' =>'Irma',
                'last_name' => 'Rael',
                'birthday' => '1989-10-29',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 40,
                'email' => 'ileana.erion@hotmail.com',
                'password' => '$2y$10$CJyrLyGJp4uFTRU5Wo1g9ujSuWYJCDl0QtENPpjfX1L2/qCAhe95K',
                'first_name' =>'Ileana',
                'last_name' => 'Erion',
                'birthday' => '1990-02-05',
                'rides' => 4,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 41,
                'email' => 'alyce.luedke@hotmail.com',
                'password' => '$2y$10$ZCG4jQwujvHPXiGr5npCkOLoVeH3pb/Zgcwt8vGZP.k1slvy4rih2',
                'first_name' =>'Alyce',
                'last_name' => 'Luedke',
                'birthday' => '1990-03-17',
                'rides' => 0,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 42,
                'email' => 'alphonso.gisi@gmail.com',
                'password' => '$2y$10$fBsUgD7fu1IO6AqWfuRXZOT9fsjMDrdCzl..mvJtBgNPrzdElM3zi',
                'first_name' =>'Alphonso',
                'last_name' => 'Gisi',
                'birthday' => '1991-04-25',
                'rides' => 5,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 43,
                'email' => 'chantal.haile@outlook.com',
                'password' => '$2y$10$4AifmiQZLryb2Sx6do1JQOKRxHhFJQ4fF3rD2JKhniX7iR708UwuW',
                'first_name' =>'Chantal',
                'last_name' => 'Haile',
                'birthday' => '1993-02-19',
                'rides' => 7,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 44,
                'email' => 'shaunta.bosworth@gmail.com',
                'password' => '$2y$10$ZCstliLeo02VDoGsafRNpexW/jU2frY/rkbp4x9yKxIrf4dg3kUsW',
                'first_name' =>'Shaunta',
                'last_name' => 'Bosworth',
                'birthday' => '1994-10-12',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 45,
                'email' => 'ricki.lapine@yahoo.com',
                'password' => '$2y$10$d8bQPXGLB8YLmG7jUz9KLumuuVLQKO.x6JJLmy3W/2L9Bw1atyV3i',
                'first_name' =>'Ricki',
                'last_name' => 'Lapine',
                'birthday' => '1994-11-21',
                'rides' => 19,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 46,
                'email' => 'albertina.tuohy@hotmail.com',
                'password' => '$2y$10$2NeZQ4tHAMGCsqNBwH8I5.90ITAyWH9hYvn/BwwiNuVcSUg.XAyGq',
                'first_name' =>'Albertina',
                'last_name' => 'Tuohy',
                'birthday' => '1996-05-08',
                'rides' => 14,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 47,
                'email' => 'siobhan.plourde@hotmail.com',
                'password' => '$2y$10$tLCochP70xmWZbjeLReSvuHnWN0sY14FD0eXGswF829Pjy7kHKfsy',
                'first_name' =>'Siobhan',
                'last_name' => 'Plourde',
                'birthday' => '1997-05-05',
                'rides' => 19,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 48,
                'email' => 'valrie.heims@aol.com',
                'password' => '$2y$10$rHau4SeaiUi6yyTfM2rifOwEwcKIvOgloUQtrtB82wvQce9o90eBS',
                'first_name' =>'Valrie',
                'last_name' => 'Heims',
                'birthday' => '1997-07-07',
                'rides' => 22,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 49,
                'email' => 'chaya.mccarron@aol.com',
                'password' => '$2y$10$wP9N5AW5x8X7VAMSKJAdveFQAwGGr1cos9lUjBBlRCfSHn0fAXZtO',
                'first_name' =>'Chaya',
                'last_name' => 'Mccarron',
                'birthday' => '1998-01-09',
                'rides' => 19,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 50,
                'email' => 'corazon.brenneman@yahoo.com',
                'password' => '$2y$10$jtYve45Gt6cgNHtH1aQZUec6MAkXhmkxFcdPcHVOKj56NtcjcZHiq',
                'first_name' =>'Corazon',
                'last_name' => 'Brenneman',
                'birthday' => '1998-04-19',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 51,
                'email' => 'travis.milo@outlook.com',
                'password' => '$2y$10$f4Nc8F4flvbVtFx6HDgd.OHz914sFMxwRuw97DzdroC81OxLq5Lpy',
                'first_name' => 'Travis',
                'last_name' => 'Milo',
                'birthday' => '1971-01-05',
                'rides' => 14,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 52,
                'email' => 'sherilyn.laver@yahoo.com',
                'password' => '$2y$10$4IxNU7G/w2RXH3QX2wFX8.Ufat7QxF4k6xxJ1Dh7iaABteFWbBqXW',
                'first_name' => 'Sherilyn',
                'last_name' => 'Laver',
                'birthday' => '1971-01-14',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 53,
                'email' => 'myra.schwalm@yahoo.com',
                'password' => '$2y$10$fLcRXzZkU3u9lHbsVswAKOQJWB5YmaOVTH/OlRQb5P1KrB9tfm.VG',
                'first_name' => 'Myra',
                'last_name' => 'Schwalm',
                'birthday' => '1971-03-15',
                'rides' => 18,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 54,
                'email' => 'dion.mejias@hotmail.com',
                'password' => '$2y$10$B06Xfda.B5oUO9hpuojwBu6ppkHknS/UhRa13Mb8BExd6Phoj2ZaC',
                'first_name' => 'Dion',
                'last_name' => 'Mejias',
                'birthday' => '1975-09-24',
                'rides' => 16,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 55,
                'email' => 'domenica.norrell@aol.com',
                'password' => '$2y$10$bp923J3zYzscupAjE94yd.C3BDpnythlfKTDPu28a497BpWPfX/Ae',
                'first_name' => 'Domenica',
                'last_name' => 'Norrell',
                'birthday' => '1978-05-06',
                'rides' => 5,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 56,
                'email' => 'shaunda.ruby@outlook.com',
                'password' => '$2y$10$EmLXfHb.3MdtZKjGa98.Oul2rauacrtrsYRFYz6UYaXfY/PPl0BP6',
                'first_name' => 'Shaunda',
                'last_name' => 'Ruby',
                'birthday' => '1978-10-11',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 57,
                'email' => 'gloria.mell@gmail.com',
                'password' => '$2y$10$34zaNvB9TslFkT0m/3IoR.vT2FhIWCpJY6GqkrIwCcsFwBttlekKy',
                'first_name' => 'Gloria',
                'last_name' => 'Mell',
                'birthday' => '1981-06-18',
                'rides' => 14,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 58,
                'email' => 'quintin.pasley@aol.com',
                'password' => '$2y$10$xn5iEAuOB/Huoy7aONoOuuaAuaR.PDWmD.aJUmMzkrDvZIiMkr5/2',
                'first_name' => 'Quintin',
                'last_name' => 'Pasley',
                'birthday' => '1982-04-13',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 59,
                'email' => 'melanie.yong@gmail.com',
                'password' => '$2y$10$bf5cOpPjefGtbBqdOeW0N.xFbGkDtnh2bliJ1jW6fPPchPGgIyLLO',
                'first_name' => 'Melanie',
                'last_name' => 'Yong',
                'birthday' => '1982-07-23',
                'rides' => 24,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 60,
                'email' => 'keneth.prude@gmail.com',
                'password' => '$2y$10$3pl54cUouJg5SqXo//0UA.SzqYNxJJZhBVw.z8Bfi/yi0r.l9WYe.',
                'first_name' => 'Keneth',
                'last_name' => 'Prude',
                'birthday' => '1984-06-30',
                'rides' => 13,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 61,
                'email' => 'stacia.greenburg@yahoo.com',
                'password' => '$2y$10$N7gFWeFheWovVeQgoah9EOlcKdlJ87blaqzmE11C8CIp9lPWMXB1G',
                'first_name' => 'Stacia',
                'last_name' => 'Greenburg',
                'birthday' => '1984-12-22',
                'rides' => 11,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 62,
                'email' => 'wayne.edwin@outlook.com',
                'password' => '$2y$10$n.SZrK8YHEnek7Bx4Cjw9.BcOw.o/qtWaNCoMyDDHvZqvXpL2Atp6',
                'first_name' => 'Wayne',
                'last_name' => 'Edwin',
                'birthday' => '1985-11-14',
                'rides' => 10,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 63,
                'email' => 'oneida.shirey@gmail.com',
                'password' => '$2y$10$.WdOEhNNSourUqwg3wMb6.Z.ICdrSsPLrin2tidRwBcmy4oumJGRS',
                'first_name' => 'Oneida',
                'last_name' => 'Shirey',
                'birthday' => '1987-01-15',
                'rides' => 3,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 64,
                'email' => 'joy.klingensmith@yahoo.com',
                'password' => '$2y$10$/Py40jz7rAavHDEjESx3SOZcEJ74Cdw8l4FyrkgAL6O.b9WuDQbSC',
                'first_name' => 'Joy',
                'last_name' => 'Klingensmith',
                'birthday' => '1988-03-18',
                'rides' => 18,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 65,
                'email' => 'lorita.lebsock@gmail.com',
                'password' => '$2y$10$Ue6f.6.7LsxQcaj2clO6L.KFFZ9Jwn0DVqrBTy0vZ57CTGkbBCDdi',
                'first_name' => 'Lorita',
                'last_name' => 'Lebsock',
                'birthday' => '1990-02-23',
                'rides' => 6,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 66,
                'email' => 'deloras.sprayberry@outlook.com',
                'password' => '$2y$10$9Vt.Mu3k2a0SNtfBg7nNjeRCv4Zy7dEmWitPuR6UJVfVXitPuN/N2',
                'first_name' => 'Deloras',
                'last_name' => 'Sprayberry',
                'birthday' => '1990-11-11',
                'rides' => 11,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 67,
                'email' => 'miyoko.overall@outlook.com',
                'password' => '$2y$10$8LDyS1dDk5s7ll.ZqTtLTOzGdF83BarsE.qXk6XFYnTyHQvgeWO6G',
                'first_name' => 'Miyoko',
                'last_name' => 'Overall',
                'birthday' => '1992-02-23',
                'rides' => 7,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 68,
                'email' => 'carmelita.pray@hotmail.com',
                'password' => '$2y$10$cUPJSNbl1/BlkoeJPR3WZeBsbyC2N64bh/UOkFsLI8F7g6KfWqnGu',
                'first_name' => 'Carmelita',
                'last_name' => 'Pray',
                'birthday' => '1992-06-08',
                'rides' => 14,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 69,
                'email' => 'landon.mannino@yahoo.com',
                'password' => '$2y$10$HPZ7Q.5T3vWHbjP6re0E6.CgENfnTAHgegHGKBLOt0nYTFQSN.bH.',
                'first_name' => 'Landon',
                'last_name' => 'Mannino',
                'birthday' => '1993-05-06',
                'rides' => 17,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 70,
                'email' => 'sandi.nordberg@outlook.com',
                'password' => '$2y$10$TDNBXyVjylSHEINLoZn9R.DpzKhDVUaciGo2r9AuWgbU5koqzrSuK',
                'first_name' => 'Sandi',
                'last_name' => 'Nordberg',
                'birthday' => '1995-04-17',
                'rides' => 4,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 71,
                'email' => 'gregg.cregan@aol.com',
                'password' => '$2y$10$1yNyrBOXkuMM.BSi8EtRMeg59WDAPiXey/HaJPKXxs4LidAkhDsae',
                'first_name' => 'Gregg',
                'last_name' => 'Cregan',
                'birthday' => '1996-04-25',
                'rides' => 10,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 72,
                'email' => 'concepcion.ardrey@hotmail.com',
                'password' => '$2y$10$1xcViAcrghmt0liaJI/EyuMnDz0wDLFDGSmjfa9/WB3t84gZ5GrM6',
                'first_name' => 'Concepcion',
                'last_name' => 'Ardrey',
                'birthday' => '1997-04-25',
                'rides' => 18,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 73,
                'email' => 'karly.quarterman@yahoo.com',
                'password' => '$2y$10$s1WstxCc/jYsHGmzxmVlQ.aZDI8DNOjj6BSQiU8nQboOHzoX8qpb.',
                'first_name' => 'Karly',
                'last_name' => 'Quarterman',
                'birthday' => '1997-05-15',
                'rides' => 0,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 74,
                'email' => 'delois.williford@aol.com',
                'password' => '$2y$10$Rra/PGdsyUV63w/QD/ea8O55CdcfQ1JNW3KWmMmxa.kfP6OziVfje',
                'first_name' => 'Delois',
                'last_name' => 'Williford',
                'birthday' => '1997-09-29',
                'rides' => 8,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 75,
                'email' => 'roni.denison@aol.com',
                'password' => '$2y$10$NNiGQlC6YcHqCVB9//nj5eupJ7WCOi.94mQD0zsYrYqHCBSFl5HCS',
                'first_name' => 'Roni',
                'last_name' => 'Denison',
                'birthday' => '1998-05-28',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 76,
                'email' => 'marita.mckendrick@aol.com',
                'password' => '$2y$10$wKlSjnvD70504P6mCPo77OzOyzfxJB6l/e4W9ukBM/58wwjPK7Iyi',
                'first_name' => 'Marita',
                'last_name' => 'Mckendrick',
                'birthday' => '1971-07-26',
                'rides' => 20,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 77,
                'email' => 'jackqueline.stangle@aol.com',
                'password' => '$2y$10$NV.o1dX0AMz13SDqjw9hduMW7JCPwR/R6SJawLeo2tsfGO/bbmd8e',
                'first_name' => 'Jackqueline',
                'last_name' => 'Stangle',
                'birthday' => '1972-02-06',
                'rides' => 8,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 78,
                'email' => 'katrina.burghart@outlook.com',
                'password' => '$2y$10$L6QauFC8TkpCzPQd6YxA.O3djhbCIXgfz1JFS4ZFqT1oGGXcHhvLi',
                'first_name' => 'Katrina',
                'last_name' => 'Burghart',
                'birthday' => '1972-08-31',
                'rides' => 23,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 79,
                'email' => 'alpha.burtner@gmail.com',
                'password' => '$2y$10$hsgBODXoYtE5Saif9j0uCOCCXwPYr5iTOkeWmxN.LzU/EyuWXcZBy',
                'first_name' => 'Alpha',
                'last_name' => 'Burtner',
                'birthday' => '1975-06-28',
                'rides' => 20,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 80,
                'email' => 'katheleen.karsten@yahoo.com',
                'password' => '$2y$10$WFx8Zq4VLYeuRpSC4Vedz.BeGW9PyaVqKeKAE/ZbxojwbE2Wayhde',
                'first_name' => 'Katheleen',
                'last_name' => 'Karsten',
                'birthday' => '1975-11-06',
                'rides' => 5,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 81,
                'email' => 'trinity.fetterman@hotmail.com',
                'password' => '$2y$10$e.yb9anGppQQJzRnaAIWQeR3NCrEhuuj/8GbIkROQQ2.fbjDHf9uK',
                'first_name' => 'Trinity',
                'last_name' => 'Fetterman',
                'birthday' => '1977-05-11',
                'rides' => 10,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 82,
                'email' => 'tressa.janes@outlook.com',
                'password' => '$2y$10$BfbhMuLbBUfNsOoYgP6Fb.DMYwv6G/qm.CGl0EbbVDOyiPXWTcmii',
                'first_name' => 'Tressa',
                'last_name' => 'Janes',
                'birthday' => '1977-08-06',
                'rides' => 16,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 83,
                'email' => 'roberta.baltz@outlook.com',
                'password' => '$2y$10$wfAVqYcrnTretcfNkkIrG.4EMOicMkjZROBURqxxNro0SeoFVr1fe',
                'first_name' => 'Roberta',
                'last_name' => 'Baltz',
                'birthday' => '1977-11-06',
                'rides' => 16,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 84,
                'email' => 'lashanda.ramthun@yahoo.com',
                'password' => '$2y$10$t9JIiu1q61mZpYWwkakFkeHURAQJcmCNehFZmD9BZDUYLj29jJ7F6',
                'first_name' => 'Lashanda',
                'last_name' => 'Ramthun',
                'birthday' => '1978-06-10',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 85,
                'email' => 'madelyn.bellantoni@hotmail.com',
                'password' => '$2y$10$F3hvpLMV/qNEO3thHHTwHOdkE3cwAvsKYBswY.Az1PrdxhwsZfEw2',
                'first_name' => 'Madelyn',
                'last_name' => 'Bellantoni',
                'birthday' => '1979-07-09',
                'rides' => 5,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 86,
                'email' => 'shawana.younker@outlook.com',
                'password' => '$2y$10$6QaIjmmYmGwOjmpxUjSN2OBSJ16mgz5m816zZDU34pDt2H/W7LBLG',
                'first_name' => 'Shawana',
                'last_name' => 'Younker',
                'birthday' => '1979-10-10',
                'rides' => 24,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 87,
                'email' => 'carmelo.marquart@outlook.com',
                'password' => '$2y$10$yWGgw7wB7V1F6sOpS4BnkuMy/y.5bWqU31dJRZ/6m83NMssORdVLO',
                'first_name' => 'Carmelo',
                'last_name' => 'Marquart',
                'birthday' => '1982-02-07',
                'rides' => 5,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 88,
                'email' => 'sung.miller@gmail.com',
                'password' => '$2y$10$OyAeVyit3SVyH5RKIVimle1AxUGYwWH4JuA6DwyBoJZ./eObPoaDS',
                'first_name' => 'Sung',
                'last_name' => 'Miller',
                'birthday' => '1983-07-15',
                'rides' => 2,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 89,
                'email' => 'clorinda.velasques@outlook.com',
                'password' => '$2y$10$9h5DyZJa.AkqqkrrhyrQ7.Dy6y0ed2.EKX1JJJk3RRP0BkhlZ.Zea',
                'first_name' => 'Clorinda',
                'last_name' => 'Velasques',
                'birthday' => '1984-04-06',
                'rides' => 2,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 90,
                'email' => 'ji.isreal@yahoo.com',
                'password' => '$2y$10$9dAZquEbUsGgwYClfj93wOYNc77iJDZiLhcF8cyr5LxM6oKtofBLm',
                'first_name' => 'Ji',
                'last_name' => 'Isreal',
                'birthday' => '1984-05-12',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 91,
                'email' => 'jina.walton@yahoo.com',
                'password' => '$2y$10$riW5zaqu9jBPiiMwwTRDCewIi0ilUTT9yBCaDcR9KOfOHQw7OBzVO',
                'first_name' => 'Jina',
                'last_name' => 'Walton',
                'birthday' => '1986-06-21',
                'rides' => 15,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 92,
                'email' => 'luciano.galeano@outlook.com',
                'password' => '$2y$10$jYsewWXgDBhfOWYGU7ipmeer.pXyQbiTfZ9GNFIB8uOkIMS4sR356',
                'first_name' => 'Luciano',
                'last_name' => 'Galeano',
                'birthday' => '1986-12-05',
                'rides' => 12,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 93,
                'email' => 'laureen.buie@yahoo.com',
                'password' => '$2y$10$IgP5kaKt41qYoCr.bKkDPuzZq5AcrFWF9oO6nwQD6zoUOUaxST3Bu',
                'first_name' => 'Laureen',
                'last_name' => 'Buie',
                'birthday' => '1988-08-30',
                'rides' => 0,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 94,
                'email' => 'anja.tobia@hotmail.com',
                'password' => '$2y$10$0SHS2PMlayacTjhJC/55k.DIMkEV2tEq2U4LjxHA6AxXzZ/jzjeLm',
                'first_name' => 'Anja',
                'last_name' => 'Tobia',
                'birthday' => '1990-08-16',
                'rides' => 9,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 95,
                'email' => 'pierre.boyd@hotmail.com',
                'password' => '$2y$10$.M0SL3IbiKmTJ.tU0P46WuJbqZYrepG20bATpdEW0HJekMUn4gCUa',
                'first_name' => 'Pierre',
                'last_name' => 'Boyd',
                'birthday' => '1993-01-25',
                'rides' => 2,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 96,
                'email' => 'ervin.koehl@aol.com',
                'password' => '$2y$10$jObILXjo8IVAxWHF3x0syeSdpMzhdRdBHKtULxdBAAOrsRAMdnUkO',
                'first_name' => 'Ervin',
                'last_name' => 'Koehl',
                'birthday' => '1993-12-07',
                'rides' => 8,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 97,
                'email' => 'fabian.schoenberg@aol.com',
                'password' => '$2y$10$fQ6dFfItd.vwj.Ho73hjvuXyzJABd5pK4ZGxh9yaLQnBsTdCL8QaW',
                'first_name' => 'Fabian',
                'last_name' => 'Schoenberg',
                'birthday' => '1996-07-25',
                'rides' => 1,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 98,
                'email' => 'sarina.carrington@aol.com',
                'password' => '$2y$10$HYvKaMjKp5Q.iMjGe1NIJuRYAvTgVE1VYiU97YCYntNFwT0Yj/MNm',
                'first_name' => 'Sarina',
                'last_name' => 'Carrington',
                'birthday' => '1997-03-05',
                'rides' => 24,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 99,
                'email' => 'josef.tsosie@outlook.com',
                'password' => '$2y$10$kBl6.kyfKgop35jemFLvIuucvacHlwYi9iBJqCjud/d6kR/Q4PrpW',
                'first_name' => 'Josef',
                'last_name' => 'Tsosie',
                'birthday' => '1999-08-30',
                'rides' => 21,
                'created_at' => '2018-10-21 20:11:00',
            ],
            [
                'id' => 100,
                'email' => 'ruthie.fisler@yahoo.com',
                'password' => '$2y$10$ioZvPm7eaO6.N8bX1nNPue.y/.NPSLMnoP.6r8Pg54O2dua7o.Nsm',
                'first_name' => 'Ruthie',
                'last_name' => 'Fisler',
                'birthday' => '2000-06-12',
                'rides' => 24,
                'created_at' => '2018-10-21 20:11:00',
            ],
        ];

        $users = $this->table('users');
        $users->insert($data)
              ->save();
    }

    private function seedBikes()
    {
        $data = [
            // Front row
            [
                'id' => 1,
                'position' =>1,
                'x_coordinate' => 0,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 2,
                'position' =>2,
                'x_coordinate' => 1,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 3,
                'position' =>3,
                'x_coordinate' => 2,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 4,
                'position' =>4,
                'x_coordinate' => 3,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 5,
                'position' =>5,
                'x_coordinate' => 4,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 6,
                'position' =>6,
                'x_coordinate' => 5,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 7,
                'position' =>7,
                'x_coordinate' => 6,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 8,
                'position' =>8,
                'x_coordinate' => 7,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 9,
                'position' =>9,
                'x_coordinate' => 8,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 10,
                'position' => 10,
                'x_coordinate' => 9,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 11,
                'position' => 11,
                'x_coordinate' => 10,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 12,
                'position' => 12,
                'x_coordinate' => 11,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 13,
                'position' => 13,
                'x_coordinate' => 12,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 14,
                'position' => 14,
                'x_coordinate' => 13,
                'y_coordinate' => 3,
                'created_at' => '2018-10-21 20:13:00',
            ],

            // Left Side Bar
            [
                'id' => 15,
                'position' => 15,
                'x_coordinate' => 4,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 16,
                'position' => 16,
                'x_coordinate' => 4,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 17,
                'position' => 17,
                'x_coordinate' => 3,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 18,
                'position' => 18,
                'x_coordinate' => 3,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 19,
                'position' => 19,
                'x_coordinate' => 2,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 20,
                'position' => 20,
                'x_coordinate' => 2,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 21,
                'position' => 21,
                'x_coordinate' => 1,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 22,
                'position' => 22,
                'x_coordinate' => 1,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 23,
                'position' => 23,
                'x_coordinate' => 0,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 24,
                'position' => 24,
                'x_coordinate' => 0,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],

            // Right Side Bar
            [
                'id' => 25,
                'position' => 25,
                'x_coordinate' => 9,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 26,
                'position' => 26,
                'x_coordinate' => 9,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],

            [
                'id' => 27,
                'position' => 27,
                'x_coordinate' => 10,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 28,
                'position' => 28,
                'x_coordinate' => 10,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 29,
                'position' => 29,
                'x_coordinate' => 11,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 30,
                'position' => 30,
                'x_coordinate' => 11,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 31,
                'position' => 31,
                'x_coordinate' => 12,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 32,
                'position' => 32,
                'x_coordinate' => 12,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 33,
                'position' => 33,
                'x_coordinate' => 13,
                'y_coordinate' => 1,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 34,
                'position' => 34,
                'x_coordinate' => 13,
                'y_coordinate' => 0,
                'created_at' => '2018-10-21 20:13:00',
            ],

            // Second Row
            [
                'id' => 35,
                'position' => 35,
                'x_coordinate' => 0,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 36,
                'position' => 36,
                'x_coordinate' => 1,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 37,
                'position' => 37,
                'x_coordinate' => 2,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 38,
                'position' => 38,
                'x_coordinate' => 3,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 39,
                'position' => 39,
                'x_coordinate' => 4,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 40,
                'position' => 40,
                'x_coordinate' => 5,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 41,
                'position' => 41,
                'x_coordinate' => 6,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 42,
                'position' => 42,
                'x_coordinate' => 7,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 43,
                'position' => 43,
                'x_coordinate' => 8,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 44,
                'position' => 44,
                'x_coordinate' => 9,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 45,
                'position' => 45,
                'x_coordinate' => 10,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 46,
                'position' => 46,
                'x_coordinate' => 11,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 47,
                'position' => 47,
                'x_coordinate' => 12,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 48,
                'position' => 48,
                'x_coordinate' => 13,
                'y_coordinate' => 4,
                'created_at' => '2018-10-21 20:13:00',
            ],

            // Back Row
            [
                'id' => 49,
                'position' => 49,
                'x_coordinate' => 0,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 50,
                'position' => 50,
                'x_coordinate' => 1,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 51,
                'position' => 51,
                'x_coordinate' => 2,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 52,
                'position' => 52,
                'x_coordinate' => 3,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 53,
                'position' => 53,
                'x_coordinate' => 4,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 54,
                'position' => 54,
                'x_coordinate' => 5,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 55,
                'position' => 55,
                'x_coordinate' => 6,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 56,
                'position' => 56,
                'x_coordinate' => 7,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 57,
                'position' => 57,
                'x_coordinate' => 8,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 58,
                'position' => 58,
                'x_coordinate' => 9,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 59,
                'position' => 59,
                'x_coordinate' => 10,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 60,
                'position' => 60,
                'x_coordinate' => 11,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 61,
                'position' => 61,
                'x_coordinate' => 12,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
            [
                'id' => 62,
                'position' => 62,
                'x_coordinate' => 13,
                'y_coordinate' => 5,
                'created_at' => '2018-10-21 20:13:00',
            ],
        ];

        $bikes = $this->table('bikes');
        $bikes->insert($data)
              ->save();
    }

    private function seedReservations()
    {
        $data = [
            [
                'id' => 1,
                'bike_id' => 46,
                'user_id' => 26,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 2,
                'bike_id' => 52,
                'user_id' => 14,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 3,
                'bike_id' => 17,
                'user_id' => 2,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 4,
                'bike_id' => 6,
                'user_id' => 30,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 5,
                'bike_id' => 8,
                'user_id' => 47,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 6,
                'bike_id' => 26,
                'user_id' => 22,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 7,
                'bike_id' => 27,
                'user_id' => 29,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 8,
                'bike_id' => 45,
                'user_id' => 28,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 9,
                'bike_id' => 48,
                'user_id' => 18,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 10,
                'bike_id' => 5,
                'user_id' => 5,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 11,
                'bike_id' => 42,
                'user_id' => 44,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 12,
                'bike_id' => 59,
                'user_id' => 32,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 13,
                'bike_id' => 29,
                'user_id' => 7,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 14,
                'bike_id' => 58,
                'user_id' => 3,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 15,
                'bike_id' => 24,
                'user_id' => 40,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 16,
                'bike_id' => 16,
                'user_id' => 19,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 17,
                'bike_id' => 4,
                'user_id' => 49,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 18,
                'bike_id' => 23,
                'user_id' => 46,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 19,
                'bike_id' => 33,
                'user_id' => 31,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 20,
                'bike_id' => 9,
                'user_id' => 35,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 21,
                'bike_id' => 60,
                'user_id' => 39,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 22,
                'bike_id' => 3,
                'user_id' => 50,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 23,
                'bike_id' => 56,
                'user_id' => 36,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 24,
                'bike_id' => 49,
                'user_id' => 8,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 25,
                'bike_id' => 41,
                'user_id' => 10,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 26,
                'bike_id' => 14,
                'user_id' => 1,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 27,
                'bike_id' => 10,
                'user_id' => 48,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 28,
                'bike_id' => 28,
                'user_id' => 6,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 29,
                'bike_id' => 20,
                'user_id' => 33,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 30,
                'bike_id' => 32,
                'user_id' => 17,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 31,
                'bike_id' => 25,
                'user_id' => 4,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 32,
                'bike_id' => 51,
                'user_id' => 16,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 33,
                'bike_id' => 31,
                'user_id' => 20,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 34,
                'bike_id' => 15,
                'user_id' => 25,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 35,
                'bike_id' => 40,
                'user_id' => 21,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 36,
                'bike_id' => 53,
                'user_id' => 27,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 37,
                'bike_id' => 12,
                'user_id' => 23,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 38,
                'bike_id' => 18,
                'user_id' => 12,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 39,
                'bike_id' => 1,
                'user_id' => 43,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 40,
                'bike_id' => 44,
                'user_id' => 15,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 41,
                'bike_id' => 39,
                'user_id' => 13,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 42,
                'bike_id' => 62,
                'user_id' => 11,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 43,
                'bike_id' => 55,
                'user_id' => 9,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 44,
                'bike_id' => 38,
                'user_id' => 37,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 45,
                'bike_id' => 13,
                'user_id' => 41,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 46,
                'bike_id' => 11,
                'user_id' => 34,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 47,
                'bike_id' => 36,
                'user_id' => 24,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 48,
                'bike_id' => 2,
                'user_id' => 42,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 49,
                'bike_id' => 34,
                'user_id' => 45,
                'created_at' => '2018-10-22 11:58:00',
            ],
            [
                'id' => 50,
                'bike_id' => 43,
                'user_id' => 38,
                'created_at' => '2018-10-22 11:58:00',
            ],
        ];

        $reservations = $this->table('reservations');
        $reservations->insert($data)
              ->save();
    }
}
