version: '3'

services:
  global-redis:
    container_name: global-redis
    image: redis:3.2.11-alpine
    ports:
      - "63798:6379"
    networks:
      - localenv_network

networks:
  localenv_network:
    external: true
